### PR TITLE
Update footer.html.twig

### PR DESCRIPTION
**Pull request by Habmala**
Implements #26 
Add support for rel=me in social media links in the footer.

### CODE REVIEW

**Comment by ParitoshBh** [comment]
Looks good! Could you also update [Configuration section of README](https://github.com/ParitoshBh/grav-coder/blob/master/README.md#customizations) (under `social`) to include the new option? Less likely to be used but it is better to have it documented. Eg,
```
  twitter:
    title: Twitter
    url: <url>
    icon: fa-twitter
    rel: me (disabled by default)
```
or something along the lines.

Thanks!

**Comment by Habmala** [comment]
Absolutely. I'll look at it over the weekend.

**Comment by Habmala** [comment]
Sorry it took so long. I edited the readme. I didn't do it exactly like you suggested, I hope it's OK anyway, let me know otherwise. Not sure I managed to push the update properly, let me know if it's not showing up.

Thanks
// Habmala

**Comment by ParitoshBh** [comment]
Looks good. Thanks!

**Review by ParitoshBh — APPROVED** [review]

**Pull request merged**
